CREATE TABLE PROTELDBNEW.EG_CUSTOMER_INFO (
  ID	SMALLINT	NOT NULL,
  FIRSTNAME	VARCHAR(20)	NOT NULL,
  LASTNAME	VARCHAR(20)	NOT NULL,
  DEPARTMENT	VARCHAR(20),
  JOBTITLE	VARCHAR(20)
  ) 
  IN IBMDB2SAMPLEREL
  ORGANIZE BY ROW;

ALTER TABLE PROTELDBNEW.EG_CUSTOMER_INFO
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMIT;

RUNSTATS ON TABLE PROTELDBNEW.EG_CUSTOMER_INFO
	ALLOW WRITE ACCESS;


